# add ~/.bash_profile if needed for executing ~/.bashrc
if [ -e ~/.bashrc -a ! -e ~/.bash_profile -a ! -e ~/.bash_login -a ! -e ~/.profile ]; then
  printf "\n\033[31mWARNING: Found ~/.bashrc but no ~/.bash_profile, ~/.bash_login or ~/.profile.\033[m\n\n"
  echo "This looks like an incorrect setup."
  echo "A ~/.bash_profile that loads ~/.bashrc will be created for you."
  cat >~/.bash_profile <<-\EOF
	# generated by Git for Windows
	test -f ~/.profile && . ~/.profile
	test -f ~/.bashrc && . ~/.bashrc
	EOF
fi

PATH=/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/core_perl:/usr/bin/vendor_perl

mkdir -p $USERPROFILE/oithomes/java18/javaexc/
export PATH=/c/oit/openjdk1.8.0.181/bin/:$PATH
export HOME=$(cd "$USERPROFILE\oithomes\java18" && pwd)

export PROMPT_COMMAND="history -a"
HISTFILE=$HOME/javaexc/.java_bash_history.`date "+%Y%m%d"`
HISTTIMEFORMAT="%Y/%m/%dT%T%z "