# add ~/.bash_profile if needed for executing ~/.bashrc
if [ -e ~/.bashrc -a ! -e ~/.bash_profile -a ! -e ~/.bash_login -a ! -e ~/.profile ]; then
  printf "\n\033[31mWARNING: Found ~/.bashrc but no ~/.bash_profile, ~/.bash_login or ~/.profile.\033[m\n\n"
  echo "This looks like an incorrect setup."
  echo "A ~/.bash_profile that loads ~/.bashrc will be created for you."
  cat >~/.bash_profile <<-\EOF
	# generated by Git for Windows
	test -f ~/.profile && . ~/.profile
	test -f ~/.bashrc && . ~/.bashrc
	EOF
fi

PATH=/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/core_perl:/usr/bin/vendor_perl
export LANG="ja_JP.UTF-8"

mkdir -p $USERPROFILE/oithomes/java/kadai/`/usr/local/bin/course`/
export PATH=/c/oit/openjdk1.8.0.181/bin/:$PATH
export PATH=/c/oit/VSCode-win32-x64-1.31.0/bin/:$PATH
export HOME=$(cd "$USERPROFILE\oithomes\java" && pwd)

export PROMPT_COMMAND='echo -e "res:$?\tpwd:`pwd`\tdate:`date +%s`\t" >> $HOME/kadai/`/usr/local/bin/course`/.java_bash_history.`date +'%Y%m'`;history -a'
HISTFILE=$HOME/kadai/`/usr/local/bin/course`/.java_bash_history.`date +'%Y%m'`
HISTTIMEFORMAT="%Y/%m/%dT%T%z "
