# add ~/.bash_profile if needed for executing ~/.bashrc
if [ -e ~/.bashrc -a ! -e ~/.bash_profile -a ! -e ~/.bash_login -a ! -e ~/.profile ]; then
  printf "\n\033[31mWARNING: Found ~/.bashrc but no ~/.bash_profile, ~/.bash_login or ~/.profile.\033[m\n\n"
  echo "This looks like an incorrect setup."
  echo "A ~/.bash_profile that loads ~/.bashrc will be created for you."
  cat >~/.bash_profile <<-\EOF
	# generated by Git for Windows
	test -f ~/.profile && . ~/.profile
	test -f ~/.bashrc && . ~/.bashrc
	EOF
fi

PATH=/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/core_perl:/usr/bin/vendor_perl
export LANG="ja_JP.UTF-8"

mkdir -p $USERPROFILE/oithomes/java/kadai/`/usr/local/bin/course`/.log/
export PATH=/c/oit/`/usr/local/bin/coursejdk`/bin/:$PATH
export PATH=/c/oit/`/usr/local/bin/coursevscode`/:$PATH
export HOME=$(cd "$USERPROFILE\oithomes\java" && pwd)

export HISTDATE=`date +'%Y%m'`
export COURSEYEAR=`/usr/local/bin/course`
HISTFILE=$HOME/kadai/$COURSEYEAR/.log/.java_bash_history.$HISTDATE
HISTTIMEFORMAT="%Y/%m/%dT%T%z "
export PROMPT_COMMAND='echo -e "res:$?\tpwd:$PWD" >> $HOME/kadai/$COURSEYEAR/.log/.java_bash_history.$HISTDATE;history -a'
